#! /bin/bash
#
# Setup script for building and testing the project
#
set -eu

for switch in $(cat .circleci/opam-switches); do
  echo "Test dune-deps with opam switch $switch."
  git clean -dfx
  opam switch "$switch"
  eval $(opam env)
  make test
  echo "Successfully tested dune-deps with opam switch $switch."
done
