#! /bin/bash
#
# Setup script for building and testing the project
#
set -eu

for switch in $(cat .circleci/opam-switches); do
  echo "Testing with opam switch $switch"

  echo "Check for Bytes.blit_string"
  echo 'let f = Bytes.blit_string' > /tmp/compat.ml
  ocaml /tmp/compat.ml

  git clean -dfx
  opam switch "$switch"
  eval $(opam env)
  make test
done
