#! /bin/bash
#
# Setup script for building and testing the project
#
set -eu

sudo apt-get install m4 -y

opam repo add --all -k git github https://github.com/ocaml/opam-repository.git

for switch in $(cat .circleci/opam-switches); do
  echo "Installing dependencies with opam switch $switch"
  opam switch "$switch"
  eval $(opam env)
  opam update
  opam install -y dune sexplib
done
