#! /bin/bash
#
# Setup script for building and testing the project
#
set -eu

sudo apt-get install m4 -y

opam repo add --all -k git github https://github.com/ocaml/opam-repository.git

# temporary; use opam package when it becomes available
(
  cd /tmp
  git clone https://github.com/diml/dune-file.git
)

for switch in $(cat .circleci/opam-switches); do
  echo "Installing dependencies with opam switch $switch"
  opam switch "$switch"
  eval $(opam env)
  opam update
  opam install -y dune sexplib alcotest cmdliner

  opam install -y pp
  (
    cd /tmp/dune-file
    git clean -dfX
    make
    make install
  )
done
